fix: add one-time SDDM user creation service
wayblueorg/wayblue pull request #37
Opened 2024-03-31 22:23 UTC by michaelhaaf

Run a oneshot systemd process to create sddm user before SDDM starts. Only necessary for systemds based on ublue-os/base or others without a preconfigured desktop environment.

Added to non-sway recipes.

See:
- https://github.com/ublue-os/main/issues/224#issuecomment-1987851271
- https://github.com/ublue-os/cinnamon/blob/bf44562ddbed670cdd0d03a45ea08bdb8a6e96a7/system_files/usr/lib/systemd/system/ublue-lightdm-workaround.service#L4

2024-03-31 22:32 UTC, qoijjj requested changes

2024-03-31 22:32 UTC, qoijjj commented on config/recipe-wayfire-nvidia-gdm.yml
> +  - from-file: common-systemd.yml
The -gdm images don't have sddm, they have gdm, so this shouldn't be included for those

2024-03-31 22:32 UTC, qoijjj commented on config/systemd/system/sddm-boot.service
> +ExecStart=/usr/sbin/groupadd -r sddm
let's move this to a script and follow the same pattern as in https://github.com/ublue-os/cinnamon/blob/bf44562ddbed670cdd0d03a45ea08bdb8a6e96a7/system_files/usr/etc/ublue-lightdm-workaround.sh#L6

by checking getent first

2024-04-02 04:51 UTC, RoyalOughtness commented on config/systemd/system/sddm-boot.service
> +ExecStart=/etc/sddm/sddm-useradd
/usr/etc?

2024-04-02 04:51 UTC, RoyalOughtness commented on config/sddm-packages.yml
> +  - qt5-qtquickcontrols2
what are these for?

2024-04-02 14:12 UTC, michaelhaaf commented on config/systemd/system/sddm-boot.service
> +ExecStart=/etc/sddm/sddm-useradd
/usr/etc is copied over to /etc/ after build, see https://blue-build.org/reference/modules/files/#_top and also https://github.com/ublue-os/cinnamon/blob/bf44562ddbed670cdd0d03a45ea08bdb8a6e96a7/system_files/usr/lib/systemd/system/ublue-lightdm-workaround.service#L4

2024-04-02 14:13 UTC, michaelhaaf commented on config/sddm-packages.yml
> +  - qt5-qtquickcontrols2
I had runtime errors without them, but now that I think of it, these are dependencies of the [theme I am using](https://github.com/Kangie/sddm-sugar-candy) and probably aren't necessary.

2024-04-02 16:11 UTC, qoijjj commented on config/systemd/system/sddm-boot.service
> +ExecStart=/etc/sddm/sddm-useradd
@michaelhaaf I know, but I figured we wouldn't want to invoke a user-modifiable version. I guess it's fine though.

2024-04-02 16:11 UTC, qoijjj commented on config/sddm-packages.yml
> +  - qt5-qtquickcontrols2
Ah, no harm including them then

2024-04-02 16:12 UTC, merged

2024-04-02 18:21 UTC, michaelhaaf commented on config/systemd/system/sddm-boot.service
> +ExecStart=/etc/sddm/sddm-useradd
Oh I see, fair enough. Could refactor in the future.